version: '3.3'

services:
  caddy:
    image: caddy:latest
    restart: unless-stopped
    container_name: caddy
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./caddy/site:/srv
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - esiee-hub-network
      
volumes:
  caddy_data:
    external: true
  caddy_config:

networks: 
  esiee-hub-network: 
    external: true