version: '3'

services:
  pheurly:
    image: domesday/heurly:main
    labels:
      logging: "promtail"
      logging_jobname: "containerlogs"
    env_file:
      - .env
    ports:
      - 3000:3000
    networks:
      - heurly-network
    deploy:
      mode: replicated
      replicas: 7

networks: 
  heurly-network: 
    external: true
    attachable: true