version: '3'

services:
  heurly:
    image: domesday/heurly:beta
    labels:
      logging: "promtail"
      logging_jobname: "containerlogs"
    env_file:
      - beta.env
    networks:
      - traefik-public
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        order: start-first
        failure_action: rollback
        delay: 5s
      labels:
        - traefik.enable=true
        - traefik.docker.lbswarm=true
        - traefik.docker.network=traefik-public
        - traefik.contraint-label=traefik-public
        - traefik.http.routers.heurly-staging-http.rule=Host(`beta.heurly.fr`)
        - traefik.http.routers.heurly-staging-http.entrypoints=http
        - traefik.http.routers.heurly-staging-http.middlewares=https-redirect
        - traefik.http.routers.heurly-staging-https.rule=Host(`beta.heurly.fr`)
        - traefik.http.routers.heurly-staging-https.entrypoints=https
        - traefik.http.routers.heurly-staging-https.tls=true
        - traefik.http.routers.heurly-staging-https.tls.certresolver=le
        - traefik.http.services.heurly-staging.loadbalancer.server.port=3000

networks: 
  traefik-public:
    external: true