version: '3'

services:
  db:
    #container_name: postgres-prod
    image: postgres:14-alpine
    env_file:
      - .env
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - traefik-public
    volumes:
      - postgres_data:/var/lib/postgresql/data
    labels:
      - traefik.enable=true
      - traefik.docker.lbswarm=true
      - traefik.docker.network=traefik-public
      - traefik.contraint-label=traefik-public
      - traefik.constraint-label=traefik-public
      - traefik.tcp.routers.database-tcp.rule=HostSNI(`*`)
      - traefik.tcp.routers.database-tcp.entrypoints=postgres
      - traefik.tcp.routers.database-tcp.tls=true
      - traefik.tcp.routers.database-tcp.tls.certresolver=le
      - traefik.tcp.services.database.loadbalancer.server.port=5432
    

networks: 
  traefik-public:
    external: true

volumes:
  postgres_data:
    driver: local